gripper3f_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - H1_F1J1
    - H1_F1J2
    - H1_F1J3
    - H1_F2J1
    - H1_F2J2
    - H1_F2J3
    - H1_F3J1
    - H1_F3J2
    - H1_F3J3
  gains:
    H1_F1J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F1J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F1J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F2J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F2J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F2J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F3J1:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F3J2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    H1_F3J3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1