gripper3f_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - H1_F1J1
     - H1_F1J2
     - H1_F1J3
     - H1_F2J1
     - H1_F2J2
     - H1_F2J3
     - H1_F3J1
     - H1_F3J2
     - H1_F3J3
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.05
      H1_F1J1: {trajectory: 0.1, goal: 0.1}
      H1_F1J2: {trajectory: 0.1, goal: 0.1}
      H1_F1J3: {trajectory: 0.1, goal: 0.1}
      H1_F2J1: {trajectory: 0.1, goal: 0.1}
      H1_F2J2: {trajectory: 0.1, goal: 0.1}
      H1_F2J3: {trajectory: 0.1, goal: 0.1}
      H1_F3J1: {trajectory: 0.1, goal: 0.1}
      H1_F3J2: {trajectory: 0.1, goal: 0.1}
      H1_F3J3: {trajectory: 0.1, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
joint_group_position_controller:
  type: position_controllers/JointGroupPositionController
  joints:
     - H1_F1J1
     - H1_F1J2
     - H1_F1J3
     - H1_F2J1
     - H1_F2J2
     - H1_F2J3
     - H1_F3J1
     - H1_F3J2
     - H1_F3J3